export interface Country {
  name: string;
  code: string;
  min: number;
  max: number;
  flag?: string;
}

export const countries: Country[
  {"name": "afghanistan", "code": "+93", "min": 9, "max": 9},
  {"name": "aland_islands", "code": "+358", "min": 5, "max": 12, "flag": "\ud83c\udde6\ud83c\uddfd"},
  {"name": "albania", "code": "+355", "min": 3, "max": 9},
  {"name": "algeria", "code": "+213", "min": 8, "max": 9},
  {"name": "american_samoa", "code": "+1", "min": 10, "max": 10, "flag": "\ud83c\udde6\ud83c\uddf8"},
  {"name": "andorra", "code": "+376", "min": 6, "max": 9},
  {"name": "angola", "code": "+244", "min": 9, "max": 9},
  {"name": "anguilla", "code": "+1", "min": 10, "max": 10},
  {"name": "antigua_and_barbuda", "code": "+1", "min": 10, "max": 10},
  {"name": "argentina", "code": "+54", "min": 10, "max": 10},
  {"name": "armenia", "code": "+374", "min": 8, "max": 8},
  {"name": "aruba", "code": "+297", "min": 7, "max": 7},
  {"name": "ascension_island", "code": "+247", "min": 4, "max": 4, "flag": "\ud83c\udde6\ud83c\udde8"},
  {"name": "australia", "code": "+61", "min": 5, "max": 15},
  {"name": "austria", "code": "+43", "min": 4, "max": 13},
  {"name": "azerbaijan", "code": "+994", "min": 8, "max": 9},
  {"name": "bahamas", "code": "+1", "min": 10, "max": 10},
  {"name": "bahrain", "code": "+973", "min": 8, "max": 8},
  {"name": "bangladesh", "code": "+880", "min": 6, "max": 10},
  {"name": "barbados", "code": "+1", "min": 10, "max": 10},
  {"name": "belarus", "code": "+375", "min": 9, "max": 10},
  {"name": "belgium", "code": "+32", "min": 8, "max": 9},
  {"name": "belize", "code": "+501", "min": 7, "max": 7},
  {"name": "benin", "code": "+229", "min": 8, "max": 8},
  {"name": "bermuda", "code": "+1", "min": 10, "max": 10},
  {"name": "bhutan", "code": "+975", "min": 7, "max": 8},
  {"name": "bolivia", "code": "+591", "min": 8, "max": 8},
  {"name": "bonaire", "code": "+599", "min": 7, "max": 7, "flag": "\ud83c\udde7\ud83c\uddf6"},
  {"name": "bosnia_and_herzegovina", "code": "+387", "min": 8, "max": 9},
  {"name": "botswana", "code": "+267", "min": 7, "max": 8},
  {"name": "bouvet_island", "code": "+47", "min": 8, "max": 10, "flag": "\ud83c\udde7\ud83c\uddfb"},
  {"name": "brazil", "code": "+55", "min": 10, "max": 11},
  {"name": "british_indian_ocean_territory", "code": "+246", "min": 7, "max": 7, "flag": "\ud83c\uddee\ud83c\uddf4"},
  {"name": "british_virgin_islands", "code": "+1", "min": 10, "max": 10, "flag": "\ud83c\uddfb\ud83c\uddec"},
  {"name": "brunei", "code": "+673", "min": 7, "max": 7},
  {"name": "bulgaria", "code": "+359", "min": 7, "max": 9},
  {"name": "burkina_faso", "code": "+226", "min": 8, "max": 8},
  {"name": "burundi", "code": "+257", "min": 8, "max": 8},
  {"name": "cambodia", "code": "+855", "min": 8, "max": 9},
  {"name": "cameroon", "code": "+237", "min": 9, "max": 9},
  {"name": "canada", "code": "+1", "min": 10, "max": 10},
  {"name": "cape_verde", "code": "+238", "min": 7, "max": 7},
  {"name": "cayman_islands", "code": "+1", "min": 10, "max": 10},
  {"name": "central_african_republic", "code": "+236", "min": 8, "max": 8},
  {"name": "chad", "code": "+235", "min": 8, "max": 8},
  {"name": "chile", "code": "+56", "min": 8, "max": 9},
  {"name": "china", "code": "+86", "min": 5, "max": 12},
  {"name": "christmas_island", "code": "+61", "min": 9, "max": 9, "flag": "\ud83c\udde8\ud83c\uddfd"},
  {"name": "cocos_islands", "code": "+61", "min": 9, "max": 9, "flag": "\ud83c\udde8\ud83c\udde8"},
  {"name": "colombia", "code": "+57", "min": 8, "max": 10},
  {"name": "comoros", "code": "+269", "min": 7, "max": 7},
  {"name": "congo", "code": "+242", "min": 9, "max": 9},
  {"name": "cook_islands", "code": "+682", "min": 5, "max": 5, "flag": "\ud83c\udde8\ud83c\uddf0"},
  {"name": "costa_rica", "code": "+506", "min": 8, "max": 8},
  {"name": "croatia", "code": "+385", "min": 8, "max": 12},
  {"name": "cuba", "code": "+53", "min": 6, "max": 8},
  {"name": "curacao", "code": "+599", "min": 7, "max": 8, "flag": "\ud83c\udde8\ud83c\uddfc"},
  {"name": "cyprus", "code": "+357", "min": 8, "max": 11},
  {"name": "czech_republic", "code": "+420", "min": 4, "max": 12},
  {"name": "democratic_republic_of_the_congo", "code": "+243", "min": 9, "max": 9},
  {"name": "denmark", "code": "+45", "min": 8, "max": 8},
  {"name": "djibouti", "code": "+253", "min": 6, "max": 8},
  {"name": "dominica", "code": "+1", "min": 10, "max": 10},
  {"name": "dominican_republic", "code": "+1", "min": 10, "max": 10},
  {"name": "ecuador", "code": "+593", "min": 8, "max": 9},
  {"name": "egypt", "code": "+20", "min": 7, "max": 9},
  {"name": "el_salvador", "code": "+503", "min": 7, "max": 11},
  {"name": "equatorial_guinea", "code": "+240", "min": 9, "max": 9},
  {"name": "eritrea", "code": "+291", "min": 7, "max": 7},
  {"name": "estonia", "code": "+372", "min": 7, "max": 10},
  {"name": "eswatini", "code": "+268", "min": 7, "max": 8},
  {"name": "ethiopia", "code": "+251", "min": 9, "max": 9},
  {"name": "falkland_islands", "code": "+500", "min": 5, "max": 5, "flag": "\ud83c\uddeb\ud83c\uddf0"},
  {"name": "faroe_islands", "code": "+298", "min": 6, "max": 6, "flag": "\ud83c\uddeb\ud83c\uddf4"},
  {"name": "fiji", "code": "+679", "min": 7, "max": 7},
  {"name": "finland", "code": "+358", "min": 5, "max": 12},
  {"name": "france", "code": "+33", "min": 9, "max": 9},
  {"name": "french_guiana", "code": "+594", "min": 9, "max": 9, "flag": "\ud83c\uddec\ud83c\uddeb"},
  {"name": "french_polynesia", "code": "+689", "min": 6, "max": 6, "flag": "\ud83c\uddf5\ud83c\uddeb"},
  {"name": "french_southern_territories", "code": "+262", "min": 9, "max": 9, "flag": "\ud83c\uddf9\ud83c\uddeb"},
  {"name": "gabon", "code": "+241", "min": 6, "max": 7},
  {"name": "gambia", "code": "+220", "min": 7, "max": 7},
  {"name": "georgia", "code": "+995", "min": 9, "max": 9},
  {"name": "germany", "code": "+49", "min": 6, "max": 13},
  {"name": "ghana", "code": "+233", "min": 5, "max": 9},
  {"name": "gibraltar", "code": "+350", "min": 8, "max": 8, "flag": "\ud83c\uddec\ud83c\uddee"},
  {"name": "greece", "code": "+30", "min": 10, "max": 10},
  {"name": "greenland", "code": "+299", "min": 6, "max": 6, "flag": "\ud83c\uddec\ud83c\uddf1"},
  {"name": "grenada", "code": "+1", "min": 10, "max": 10},
  {"name": "guadeloupe", "code": "+590", "min": 9, "max": 9, "flag": "\ud83c\uddec\ud83c\uddf5"},
  {"name": "guam", "code": "+1", "min": 10, "max": 10, "flag": "\ud83c\uddec\ud83c\uddfa"},
  {"name": "guatemala", "code": "+502", "min": 8, "max": 11},
  {"name": "guernsey", "code": "+44", "min": 10, "max": 10, "flag": "\ud83c\uddec\ud83c\uddec"},
  {"name": "guinea", "code": "+224", "min": 8, "max": 9},
  {"name": "guinea_bissau", "code": "+245", "min": 7, "max": 9},
  {"name": "guyana", "code": "+592", "min": 7, "max": 7},
  {"name": "haiti", "code": "+509", "min": 8, "max": 8},
  {"name": "heard_island", "code": "+672", "min": 6, "max": 6, "flag": "\ud83c\udded\ud83c\uddf2"},
  {"name": "honduras", "code": "+504", "min": 8, "max": 8},
  {"name": "hong_kong", "code": "+852", "min": 8, "max": 9},
  {"name": "hungary", "code": "+36", "min": 8, "max": 9},
  {"name": "iceland", "code": "+354", "min": 7, "max": 9},
  {"name": "india", "code": "+91", "min": 7, "max": 10},
  {"name": "indonesia", "code": "+62", "min": 5, "max": 11},
  {"name": "iran", "code": "+98", "min": 6, "max": 10},
  {"name": "iraq", "code": "+964", "min": 8, "max": 10},
  {"name": "ireland", "code": "+353", "min": 7, "max": 10},
  {"name": "isle_of_man", "code": "+44", "min": 10, "max": 10, "flag": "\ud83c\uddee\ud83c\uddf2"},
  {"name": "israel", "code": "+972", "min": 8, "max": 9},
  {"name": "italy", "code": "+39", "min": 6, "max": 11},
  {"name": "ivory_coast", "code": "+225", "min": 10, "max": 10},
  {"name": "jamaica", "code": "+1", "min": 10, "max": 10},
  {"name": "japan", "code": "+81", "min": 5, "max": 13},
  {"name": "jersey", "code": "+44", "min": 10, "max": 10, "flag": "\ud83c\uddef\ud83c\uddea"},
  {"name": "jordan", "code": "+962", "min": 8, "max": 9},
  {"name": "kazakhstan", "code": "+7", "min": 10, "max": 10},
  {"name": "kenya", "code": "+254", "min": 9, "max": 9},
  {"name": "kiribati", "code": "+686", "min": 5, "max": 8, "flag": "\ud83c\uddf0\ud83c\uddee"},
  {"name": "kosovo", "code": "+383", "min": 8, "max": 8},
  {"name": "kuwait", "code": "+965", "min": 8, "max": 8},
  {"name": "kyrgyzstan", "code": "+996", "min": 9, "max": 9},
  {"name": "laos", "code": "+856", "min": 8, "max": 10},
  {"name": "latvia", "code": "+371", "min": 8, "max": 8},
  {"name": "lebanon", "code": "+961", "min": 7, "max": 8},
  {"name": "lesotho", "code": "+266", "min": 8, "max": 8},
  {"name": "liberia", "code": "+231", "min": 7, "max": 8},
  {"name": "libya", "code": "+218", "min": 8, "max": 9},
  {"name": "liechtenstein", "code": "+423", "min": 7, "max": 9},
  {"name": "lithuania", "code": "+370", "min": 8, "max": 8},
  {"name": "luxembourg", "code": "+352", "min": 4, "max": 11},
  {"name": "macao", "code": "+853", "min": 8, "max": 8},
  {"name": "madagascar", "code": "+261", "min": 9, "max": 9},
  {"name": "malawi", "code": "+265", "min": 7, "max": 9},
  {"name": "malaysia", "code": "+60", "min": 7, "max": 10},
  {"name": "maldives", "code": "+960", "min": 7, "max": 7},
  {"name": "mali", "code": "+223", "min": 8, "max": 8},
  {"name": "malta", "code": "+356", "min": 8, "max": 8},
  {"name": "marshall_islands", "code": "+692", "min": 7, "max": 7, "flag": "\ud83c\uddf2\ud83c\udded"},
  {"name": "martinique", "code": "+596", "min": 9, "max": 9, "flag": "\ud83c\uddf2\ud83c\uddf6"},
  {"name": "mauritania", "code": "+222", "min": 8, "max": 8},
  {"name": "mauritius", "code": "+230", "min": 7, "max": 8},
  {"name": "mayotte", "code": "+262", "min": 9, "max": 9, "flag": "\ud83c\uddfe\ud83c\uddf9"},
  {"name": "mexico", "code": "+52", "min": 10, "max": 10},
  {"name": "micronesia", "code": "+691", "min": 7, "max": 7, "flag": "\ud83c\uddeb\ud83c\uddf2"},
  {"name": "moldova", "code": "+373", "min": 8, "max": 8},
  {"name": "monaco", "code": "+377", "min": 8, "max": 9},
  {"name": "mongolia", "code": "+976", "min": 8, "max": 8},
  {"name": "montenegro", "code": "+382", "min": 8, "max": 9},
  {"name": "montserrat", "code": "+1", "min": 10, "max": 10, "flag": "\ud83c\uddf2\ud83c\uddf8"},
  {"name": "morocco", "code": "+212", "min": 9, "max": 9},
  {"name": "mozambique", "code": "+258", "min": 8, "max": 9},
  {"name": "myanmar", "code": "+95", "min": 7, "max": 10},
  {"name": "namibia", "code": "+264", "min": 7, "max": 10},
  {"name": "nauru", "code": "+674", "min": 7, "max": 7, "flag": "\ud83c\uddf3\ud83c\uddf7"},
  {"name": "nepal", "code": "+977", "min": 8, "max": 10},
  {"name": "netherlands", "code": "+31", "min": 9, "max": 9},
  {"name": "new_caledonia", "code": "+687", "min": 6, "max": 6, "flag": "\ud83c\uddf3\ud83c\udde8"},
  {"name": "new_zealand", "code": "+64", "min": 3, "max": 10},
  {"name": "nicaragua", "code": "+505", "min": 8, "max": 8},
  {"name": "niger", "code": "+227", "min": 8, "max": 8},
  {"name": "nigeria", "code": "+234", "min": 7, "max": 10},
  {"name": "niue", "code": "+683", "min": 4, "max": 4, "flag": "\ud83c\uddf3\ud83c\uddfa"},
  {"name": "norfolk_island", "code": "+672", "min": 6, "max": 6, "flag": "\ud83c\uddf3\ud83c\uddeb"},
  {"name": "north_korea", "code": "+850", "min": 6, "max": 17},
  {"name": "north_macedonia", "code": "+389", "min": 8, "max": 8},
  {"name": "northern_mariana_islands", "code": "+1", "min": 10, "max": 10, "flag": "\ud83c\uddf2\ud83c\uddf5"},
  {"name": "norway", "code": "+47", "min": 8, "max": 8},
  {"name": "oman", "code": "+968", "min": 8, "max": 8},
  {"name": "pakistan", "code": "+92", "min": 8, "max": 11},
  {"name": "palau", "code": "+680", "min": 7, "max": 7, "flag": "\ud83c\uddf5\ud83c\uddfc"},
  {"name": "palestine", "code": "+970", "min": 8, "max": 9},
  {"name": "panama", "code": "+507", "min": 7, "max": 8},
  {"name": "papua_new_guinea", "code": "+675", "min": 8, "max": 11},
  {"name": "paraguay", "code": "+595", "min": 5, "max": 9},
  {"name": "peru", "code": "+51", "min": 8, "max": 9},
  {"name": "philippines", "code": "+63", "min": 8, "max": 10},
  {"name": "pitcairn", "code": "+64", "min": 3, "max": 10, "flag": "\ud83c\uddf5\ud83c\uddf3"},
  {"name": "poland", "code": "+48", "min": 6, "max": 9},
  {"name": "portugal", "code": "+351", "min": 9, "max": 9},
  {"name": "puerto_rico", "code": "+1", "min": 10, "max": 10},
  {"name": "qatar", "code": "+974", "min": 8, "max": 8},
  {"name": "reunion", "code": "+262", "min": 9, "max": 9, "flag": "\ud83c\uddf7\ud83c\uddea"},
  {"name": "romania", "code": "+40", "min": 9, "max": 9},
  {"name": "russia", "code": "+7", "min": 10, "max": 10},
  {"name": "rwanda", "code": "+250", "min": 9, "max": 9},
  {"name": "saint_barthelemy", "code": "+590", "min": 9, "max": 9, "flag": "\ud83c\udde7\ud83c\uddf1"},
  {"name": "saint_helena", "code": "+290", "min": 4, "max": 4, "flag": "\ud83c\uddf8\ud83c\udded"},
  {"name": "saint_kitts_and_nevis", "code": "+1", "min": 10, "max": 10, "flag": "\ud83c\uddf0\ud83c\uddf3"},
  {"name": "saint_lucia", "code": "+1", "min": 10, "max": 10, "flag": "\ud83c\uddf1\ud83c\udde8"},
  {"name": "saint_martin", "code": "+590", "min": 9, "max": 9, "flag": "\ud83c\uddf2\ud83c\uddeb"},
  {"name": "saint_pierre_and_miquelon", "code": "+508", "min": 6, "max": 6, "flag": "\ud83c\uddf5\ud83c\uddf2"},
  {"name": "saint_vincent_and_the_grenadines", "code": "+1", "min": 10, "max": 10, "flag": "\ud83c\uddfb\ud83c\udde8"},
  {"name": "samoa", "code": "+685", "min": 5, "max": 7},
  {"name": "san_marino", "code": "+378", "min": 6, "max": 10},
  {"name": "sao_tome_and_principe", "code": "+239", "min": 7, "max": 7, "flag": "\ud83c\uddf8\ud83c\uddf9"},
  {"name": "saudi_arabia", "code": "+966", "min": 9, "max": 9},
  {"name": "senegal", "code": "+221", "min": 9, "max": 9},
  {"name": "serbia", "code": "+381", "min": 7, "max": 12},
  {"name": "seychelles", "code": "+248", "min": 7, "max": 7},
  {"name": "sierra_leone", "code": "+232", "min": 8, "max": 8},
  {"name": "singapore", "code": "+65", "min": 8, "max": 8},
  {"name": "sint_maarten", "code": "+1", "min": 10, "max": 10, "flag": "\ud83c\uddf8\ud83c\uddfd"},
  {"name": "slovakia", "code": "+421", "min": 4, "max": 9},
  {"name": "slovenia", "code": "+386", "min": 8, "max": 8},
  {"name": "solomon_islands", "code": "+677", "min": 5, "max": 7, "flag": "\ud83c\uddf8\ud83c\udde7"},
  {"name": "somalia", "code": "+252", "min": 7, "max": 9},
  {"name": "south_africa", "code": "+27", "min": 9, "max": 9},
  {"name": "south_georgia", "code": "+500", "min": 5, "max": 5, "flag": "\ud83c\uddec\ud83c\uddf8"},
  {"name": "south_korea", "code": "+82", "min": 8, "max": 11},
  {"name": "south_sudan", "code": "+211", "min": 9, "max": 9},
  {"name": "spain", "code": "+34", "min": 9, "max": 9},
  {"name": "sri_lanka", "code": "+94", "min": 9, "max": 9},
  {"name": "sudan", "code": "+249", "min": 9, "max": 9},
  {"name": "suriname", "code": "+597", "min": 6, "max": 7},
  {"name": "svalbard_and_jan_mayen", "code": "+47", "min": 8, "max": 8, "flag": "\ud83c\uddf8\ud83c\uddef"},
  {"name": "sweden", "code": "+46", "min": 7, "max": 13},
  {"name": "switzerland", "code": "+41", "min": 9, "max": 9},
  {"name": "syria", "code": "+963", "min": 8, "max": 9},
  {"name": "taiwan", "code": "+886", "min": 8, "max": 9},
  {"name": "tajikistan", "code": "+992", "min": 9, "max": 9},
  {"name": "tanzania", "code": "+255", "min": 9, "max": 9},
  {"name": "thailand", "code": "+66", "min": 8, "max": 9},
  {"name": "timor_leste", "code": "+670", "min": 7, "max": 7},
  {"name": "togo", "code": "+228", "min": 8, "max": 8},
  {"name": "tokelau", "code": "+690", "min": 4, "max": 4, "flag": "\ud83c\uddf9\ud83c\uddf0"},
  {"name": "tonga", "code": "+676", "min": 5, "max": 7},
  {"name": "trinidad_and_tobago", "code": "+1", "min": 10, "max": 10},
  {"name": "tunisia", "code": "+216", "min": 8, "max": 8},
  {"name": "turkey", "code": "+90", "min": 10, "max": 10},
  {"name": "turkmenistan", "code": "+993", "min": 8, "max": 8},
  {"name": "turks_and_caicos_islands", "code": "+1", "min": 10, "max": 10, "flag": "\ud83c\uddf9\ud83c\udde8"},
  {"name": "tuvalu", "code": "+688", "min": 5, "max": 6, "flag": "\ud83c\uddf9\ud83c\uddfb"},
  {"name": "uganda", "code": "+256", "min": 9, "max": 9},
  {"name": "ukraine", "code": "+380", "min": 9, "max": 9},
  {"name": "united_arab_emirates", "code": "+971", "min": 8, "max": 9},
  {"name": "united_kingdom", "code": "+44", "min": 7, "max": 10},
  {"name": "united_states", "code": "+1", "min": 10, "max": 10},
  {"name": "united_states_virgin_islands", "code": "+1", "min": 10, "max": 10, "flag": "\ud83c\uddfb\ud83c\uddee"},
  {"name": "uruguay", "code": "+598", "min": 8, "max": 8},
  {"name": "uzbekistan", "code": "+998", "min": 9, "max": 9},
  {"name": "vanuatu", "code": "+678", "min": 5, "max": 7},
  {"name": "vatican_city", "code": "+39", "min": 10, "max": 10},
  {"name": "venezuela", "code": "+58", "min": 10, "max": 10},
  {"name": "vietnam", "code": "+84", "min": 7, "max": 11},
  {"name": "wallis_and_futuna", "code": "+681", "min": 6, "max": 6, "flag": "\ud83c\uddfc\ud83c\uddeb"},
  {"name": "western_sahara", "code": "+212", "min": 9, "max": 9, "flag": "\ud83c\uddea\ud83c\udded"},
  {"name": "yemen", "code": "+967", "min": 6, "max": 9},
  {"name": "zambia", "code": "+260", "min": 9, "max": 9},
  {"name": "zimbabwe", "code": "+263", "min": 7, "max": 10}
];